// cmake_emitter.cpp
#include "cmake_emitter.hpp"

#include <sstream>

namespace logicmake {

namespace {

// A "lib" target with zero resolved sources isn't valid CMake either
// way — add_library(name) with no sources fails to configure exactly
// like the pathspec-glob bug this tool exists to avoid. In this
// schema that shape means a target standing in for something outside
// the workspace (a system library, a future find_package call —
// find_package interop is an explicit non-goal for now, see README).
// Emitting it as INTERFACE is the only shape that's both valid CMake
// and doesn't invent build steps nobody asked for; the comment makes
// the substitution visible rather than silent.
bool emitAsInterface(const TargetInfo& t) {
    return t.kind == "interface" || (t.kind == "lib" && t.sources.empty());
}

void emitTarget(std::ostringstream& out, const TargetInfo& t) {
    out << "# --- " << t.name << " ---\n";

    const bool asInterface = emitAsInterface(t);
    if (asInterface && t.kind != "interface") {
        out << "# NOTE: '" << t.name
            << "' has no resolved sources; emitted as INTERFACE rather "
               "than a real compiled library.\n";
    }

    if (asInterface) {
        out << "add_library(" << t.name << " INTERFACE)\n";
        for (const auto& inc : t.includes) {
            out << "target_include_directories(" << t.name
                << " INTERFACE " << inc << ")\n";
        }
    } else {
        out << (t.kind == "exe" ? "add_executable" : "add_library") << "("
            << t.name;
        for (const auto& src : t.sources) {
            out << " " << src;
        }
        out << ")\n";

        for (const auto& inc : t.includes) {
            out << "target_include_directories(" << t.name
                << " PUBLIC " << inc << ")\n";
        }
    }

    const char* visibility = asInterface ? " INTERFACE" : "";

    if (!t.dependsAll.empty()) {
        out << "target_link_libraries(" << t.name << visibility;
        for (const auto& dep : t.dependsAll) {
            out << " " << dep;
        }
        out << ")\n";
    }

    if (!t.links.empty()) {
        out << "target_link_libraries(" << t.name << visibility;
        for (const auto& lib : t.links) {
            out << " " << lib;
        }
        out << ")\n";
    }

    if (!t.defines.empty()) {
        out << "target_compile_definitions(" << t.name << visibility;
        for (const auto& def : t.defines) {
            out << " " << def;
        }
        out << ")\n";
    }

    out << "\n";
}

}  // namespace

std::string emitCMakeLists(const std::vector<TargetInfo>& targets,
                            const std::optional<std::string>& gitStamp) {
    std::ostringstream out;
    out << "# Generated by CppLogicMake — do not edit by hand.\n";
    out << "# Source of truth is the .pl project file this was built from.\n";
    if (gitStamp) {
        out << "# Generated from commit " << *gitStamp << "\n";
    }
    out << "cmake_minimum_required(VERSION 3.25)\n";
    out << "project(generated LANGUAGES CXX)\n\n";
    out << "set(CMAKE_CXX_STANDARD 23)\n";
    out << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n\n";

    for (const auto& t : targets) {
        if (t.cyclic) {
            out << "# WARNING: '" << t.name
                << "' participates in a dependency cycle. "
                << "Resolve before building.\n";
        }
        emitTarget(out, t);
    }

    return out.str();
}

}  // namespace logicmake
